src/Entity/Pedido.php
<?php

namespace App\Entity;

use App\Repository\PedidoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PedidoRepository::class)]
class Pedido
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_pedido = null;

    #[ORM\Column]
    private ?int $id_usuario = null;
    //el nombre que le pasamos al hacer el mappedBy debe ser el de la tabla, no el de la clase
    #[ORM\OneToMany(mappedBy: 'pedido', targetEntity: Item::class,cascade: ['persist','remove'])]
    private Collection $Items;

    #[ORM\Column(length: 400, nullable: true)]
    private ?string $destinatario = null;

    #[ORM\Column(length: 600, nullable: true)]
    private ?string $direccionDestinatario = null;

    public function __construct()
    {
        $this->Items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFechaPedido(): ?\DateTimeInterface
    {
        return $this->fecha_pedido;
    }

    public function setFechaPedido(?\DateTimeInterface $fecha_pedido): self
    {
        $this->fecha_pedido = $fecha_pedido;

        return $this;
    }

    public function getIdUsuario(): ?int
    {
        return $this->id_usuario;
    }

    public function setIdUsuario(int $id_usuario): self
    {
        $this->id_usuario = $id_usuario;

        return $this;
    }

    /**
     * @return Collection<int, Item>
     */
    public function getItems(): Collection
    {
        return $this->Items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->Items->contains($item)) {
            $this->Items->add($item);
            $item->setPedido($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->Items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getPedido() === $this) {
                $item->setPedido(null);
            }
        }

        return $this;
    }

    public function getDestinatario(): ?string
    {
        return $this->destinatario;
    }

    public function setDestinatario(?string $destinatario): self
    {
        $this->destinatario = $destinatario;

        return $this;
    }

    public function getDireccionDestinatario(): ?string
    {
        return $this->direccionDestinatario;
    }

    public function setDireccionDestinatario(?string $direccionDestinatario): self
    {
        $this->direccionDestinatario = $direccionDestinatario;

        return $this;
    }
}

src/Entity/Pregunta.php
<?php

namespace App\Entity;

use App\Repository\PreguntaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Ignore;

#[ORM\Entity(repositoryClass: PreguntaRepository::class)]
class Pregunta
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 400)]
    private ?string $nombreAutor = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $texto = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha = null;

    #[ORM\ManyToOne(inversedBy: 'preguntas')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    #[ORM\OneToMany(mappedBy: 'pregunta', targetEntity: Respuesta::class, cascade: ['persist','remove'])]
    private Collection $respuestas;

    #[ORM\ManyToOne(inversedBy: 'preguntas')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Producto $producto = null;

    public function __construct()
    {
        $this->respuestas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombreAutor(): ?string
    {
        return $this->nombreAutor;
    }

    public function setNombreAutor(string $nombreAutor): self
    {
        $this->nombreAutor = $nombreAutor;

        return $this;
    }

    public function getTexto(): ?string
    {
        return $this->texto;
    }

    public function setTexto(?string $texto): self
    {
        $this->texto = $texto;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(?\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection<int, Respuesta>
     */
    public function getRespuestas(): Collection
    {
        return $this->respuestas;
    }

    public function addRespuesta(Respuesta $respuesta): self
    {
        if (!$this->respuestas->contains($respuesta)) {
            $this->respuestas->add($respuesta);
            $respuesta->setPregunta($this);
        }

        return $this;
    }

    public function removeRespuesta(Respuesta $respuesta): self
    {
        if ($this->respuestas->removeElement($respuesta)) {
            // set the owning side to null (unless already changed)
            if ($respuesta->getPregunta() === $this) {
                $respuesta->setPregunta(null);
            }
        }

        return $this;
    }

    public function getProducto(): ?Producto
    {
        return $this->producto;
    }

    public function setProducto(?Producto $producto): self
    {
        $this->producto = $producto;

        return $this;
    }
}

src/Form/PedidoType.php
<?php

namespace App\Form;

use App\Entity\Pedido;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PedidoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            //->add('fecha_pedido')
            //->add('id_usuario')
            ->add('destinatario')
            ->add('direccionDestinatario')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pedido::class,
        ]);
    }
}

src/Controller/PedidoController.php
<?php

namespace App\Controller;

use App\Entity\Pedido;
use App\Entity\Item;
use App\Entity\Producto;
use App\Form\PedidoType;
use App\Repository\PedidoRepository;
use App\Repository\ItemRepository;
use App\Repository\ProductoRepository;
use App\Service\PedidoService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/pedido')]
class PedidoController extends AbstractController
{
    #[Route('/', name: 'app_pedido_index_all', methods: ['GET'])]
    public function indexAll(PedidoRepository $pedidoRepository): Response
    {
        try{
            return $this->render('pedido/index.html.twig', [
                'pedidos' => $pedidoRepository->findAll(),
            ]); 
        }catch(AccessDeniedHttpException $ex){
            return $this->redirectToRoute('app_producto_index', [], Response::HTTP_SEE_OTHER);
        }

    }

    #[Route('/{id}', name: 'app_pedido_index', methods: ['GET'], requirements:['id'=>'\d+'])]
    public function index(int $id,PedidoRepository $pedidoRepository): Response
    {
        return $this->render('pedido/index.html.twig', [
            'pedidos' => $pedidoRepository->findAllByUser($id),
        ]);
    }



    #[Route('/new', name: 'app_pedido_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PedidoRepository $pedidoRepository, ProductoRepository $productoRepository,PedidoService $pedidoService): Response
    {
        $pedido = new Pedido();
        $pedido->setFechaPedido(new \DateTime());
        $pedido->setIdUsuario($this->getUser()->getId());
        $pedido->setDestinatario($this->getUser()->getNombre());
        $pedido->setDireccionDestinatario($this->getUser()->getDireccion());

        //sacamos los datos de la URL
        $auxDatos="";
        $auxDatos2="";
        $datosCar = $_GET['array']; 
        $arr=array();
        $arr=explode("} {", $datosCar);

         $arrFinal=array();

        foreach($arr as $value){
            $auxDatos.=$value.",";
            
        }
        $arrDatos=explode(",", $auxDatos);
        foreach($arrDatos as $value){
            $auxDatos2.=$value.":";
            
        }
        $arrFinal=explode(":", $auxDatos2);
        //dd($arrFinal);
        //creamos el pedido con los datos que hemos sacado
        for($i=0; $i<(count($arrFinal)-2); $i+=6){
                $item1= new Item();
                $producto1= $productoRepository->findOneByNombre($arrFinal[$i+1]);
                $item1->setProducto($producto1);
                $item1->setCantidad(intval($arrFinal[$i+5]));
                $item1->setPedido($pedido);
                $pedido->addItem($item1);
            }

        $pedidoRepository->save($pedido, true);
        $pedidoService->modificarCantidadProductoDisponiblePedido($pedido);

        return $this->redirectToRoute('app_pedido_show', ['id'=>$pedido->getId()], Response::HTTP_SEE_OTHER); $pedido = new Pedido();
}

    #[Route('/show/{id}', name: 'app_pedido_show', methods: ['GET'], requirements:['id'=>'\d+'])]
    public function show(Pedido $pedido,PedidoService $pedidoService): Response
    {
        $total=$pedidoService->calcularTotal($pedido);
        return $this->render('pedido/show.html.twig', [
            'pedido' => $pedido,'total'=>$total,
        ]);
    }

    #[Route('/edit/{id}', name: 'app_pedido_edit', methods: ['GET', 'POST'], requirements:['id'=>'\d+'])]
    public function edit(Request $request, Pedido $pedido, PedidoRepository $pedidoRepository): Response
    {
        $form = $this->createForm(PedidoType::class, $pedido);
        $form->handleRequest($request); 

        if ($form->isSubmitted() && $form->isValid()) {
            $pedidoRepository->save($pedido, true);
            if (in_array('ROLE_ADMIN',$this->getUser()->getRoles())){
                return $this->redirectToRoute('app_pedido_index_all', [], Response::HTTP_SEE_OTHER);
            }else{
                return $this->redirectToRoute('app_pedido_index', ['id'=>$pedido->getIdUsuario()], Response::HTTP_SEE_OTHER);
            } 
        }

        return $this->renderForm('pedido/edit.html.twig', [
            'pedido' => $pedido,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_pedido_delete', methods: ['POST'], requirements:['id'=>'\d+'])]
    public function delete(Request $request, Pedido $pedido, PedidoRepository $pedidoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pedido->getId(), $request->request->get('_token'))) {

            $pedido=$pedidoRepository->findOneById($pedido->getId());
            $pedidoRepository->remove($pedido, true); //al eliminar el pedido, como esta 
                //configurado en cascade, se eliminan tambien todos los items asociados a 
                //ese pedido de la tabla Items
        } 
        
        if (in_array('ROLE_ADMIN',$this->getUser()->getRoles())){
            return $this->redirectToRoute('app_pedido_index_all', [], Response::HTTP_SEE_OTHER);
        }else{
            return $this->redirectToRoute('app_pedido_index', ['id'=>$this->getUser()->getId()], Response::HTTP_SEE_OTHER);
        }
        
    }

    #[Route('/{id}/{id_item}', name: 'app_item_delete', methods: ['POST'], requirements:['id'=>'\d+'])]
    public function deleteItem(Request $request, Pedido $pedido,int $id_item,ItemRepository $itemRepository,PedidoService $pedidoService): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pedido->getId(), $request->request->get('_token'))) {

            
            $item=$itemRepository->findOneById($id_item);
            $pedidoService->modificarCantidadProductoDisponibleItem($item);
            $itemRepository->remove($item,true);
        } 

        return $this->redirectToRoute('app_pedido_show', ['id'=>$pedido->getId()], Response::HTTP_SEE_OTHER);

        
    }

    #[Route('/pago/{id}', name: 'app_pedido_pago', methods: ['GET'])]
    public function formPagar(Pedido $pedido): Response
    {
        
        return $this->render('pedido/pago.html.twig', []); 
    }
}

templates/pedido/_delete_form.html.twig
<form method="post" action="{{ path('app_pedido_delete', {'id': pedido.id}) }}" onsubmit="return confirm('¿Seguro que quieres eliminar este pedido?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pedido.id) }}">
    <button class="btn btn-danger">{{ 'Eliminar'|trans }}</button>
</form>

templates/pedido/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pedido/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pedido{% endblock %}

{% block body %}
    <div class="container contenedor">
        <div class="row">
            <div class="col-xs-12 nav-btns button">
                <h1>{{ 'Modificar pedido'|trans }}</h1>
                {{ include('pedido/_form.html.twig', {'button_label': 'Actualizar datos de envio'}) }}
                {% if is_granted('ROLE_ADMIN')%}
                    <a href="{{path('app_pedido_index_all')}}"><button class="btn btn-warning">{{ 'Volver lista pedidos'|trans }}</button></a>
                {% else %}
                    <a href="{{path('app_pedido_index', {'id': app.user.id}) }}"><button class="btn btn-warning">{{ 'Volver lista pedidos'|trans }}</button></a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/pedido/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pedido index{% endblock %}

{% block body %}
<section class="bg-light p-5" id="r_lista">
    <h1>Lista de pedidos</h1>
    <div class="table-responsive" id="no-more-tables">
    <table class="table bg-white">
        <thead class="bg-dark text-light">
            <tr>
                <th>Id</th>
                <th>Fecha_pedido</th>
                <th>Id_usuario</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for pedido in pedidos %}
            <tr>
                <td data-title="Id pedido" class="registro">{{ pedido.id }}</td>
                <td data-title="Fecha env" class="registro">{{ pedido.fechaPedido ? pedido.fechaPedido|date('Y-m-d H:i:s') : '' }}</td>
                <td data-title="Id usuario" class="registro">{{ pedido.idUsuario }}</td>
                <td data-title="Botones">
                    <div class="contenedor-btn nav-btns button">
                        <a style="height: 39px" href="{{ path('app_pedido_show', {'id': pedido.id}) }}"><button class="btn btn-primary">Mostrar</button></a>
                        <a style="height: 39px" href="{{ path('app_pedido_edit', {'id': pedido.id}) }}"><button class="btn btn-warning">Actualizar</button></a>
                        {{ include('pedido/_delete_form.html.twig') }}
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
</section>
    {# <a href="{{ path('app_pedido_new') }}">Create new</a> #}
{% endblock %}

templates/pedido/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pedido{% endblock %}

{% block body %}
    <h1>Create new Pedido</h1>

    {{ include('pedido/_form.html.twig') }}

    <a href="{{ path('app_pedido_index') }}">back to list</a>
{% endblock %}

templates/pedido/pago.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulario de pago{% endblock %}

{% block body %}

<form action="#" class="credit-card-div">
<div class="panel panel-default" >
 <div class="panel-heading">
     
      <div class="row ">
              <div class="col-md-12">
                  <input type="text" class="form-control" placeholder="Introduzca numero de tarjeta" />
              </div>
          </div>
     <div class="row ">
              <div class="col-md-3 col-sm-3 col-xs-3">
                  <span class="help-block text-muted small-font" > Mes de expiracion</span>
                  <input type="text" class="form-control" placeholder="MM" />
              </div>
         <div class="col-md-3 col-sm-3 col-xs-3">
                  <span class="help-block text-muted small-font" >  Año de expiracion</span>
                  <input type="text" class="form-control" placeholder="YY" />
              </div>
        <div class="col-md-3 col-sm-3 col-xs-3">
                  <span class="help-block text-muted small-font" >  CCV</span>
                  <input type="text" class="form-control" placeholder="CCV" />
              </div>
         <div class="col-md-3 col-sm-3 col-xs-3">
                <img src="{{ asset('images/' ~ 'tarjeta.png') }}" class="img-rounded mini-imagen" alt="imagen tarjeta de credito" />
         </div>
          </div>
     <div class="row ">
              <div class="col-md-12 pad-adjust">

                  <input type="text" class="form-control" placeholder="Titular de tarjeta" />
              </div>
          </div>
     <div class="row">
<div class="col-md-12 pad-adjust">
    <div class="checkbox">
    <label>
      <input type="checkbox" checked class="text-muted"> Salvar detalles para pago rapido <a href="#"> ¿Sabe como?</a>
    </label>
  </div>
</div>
     </div>
       <div class="row nav-btns button">
            <div class="col-md-6 col-sm-6 col-xs-6 pad-adjust">
                 <a class="btn btn-warning" href="{{ path('app_pedido_index', {'id': app.user.id}) }}">Cancelar</a>
              </div>
              <div class="col-md-6 col-sm-6 col-xs-6 pad-adjust">
                  {# <input type="submit"  class="btn btn-warning btn-block" value="PAY NOW" /> #}
                  <button class="btn btn-danger">PAGAR AHORA</button>
              </div>
          </div>
     
                   </div>
              </div>
</form>

{% endblock %}

templates/pedido/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pedido{% endblock %}

{% block body %}
    <h1>Detalles pedido</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id del pedido</th>
                <td class="registro">{{ pedido.id }}</td>
            </tr>
            <tr>
                <th>Fecha_pedido</th>
                <td class="registro">{{ pedido.fechaPedido ? pedido.fechaPedido|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Nombre del destinatario</th>
                <td class="registro">{{ pedido.destinatario}}</td>
            </tr>
            <tr>
                <th>Direccion del destinatario</th>
                <td class="registro">{{ pedido.direccionDestinatario }}</td>
            </tr>
        </tbody>
    </table>

    <ul id="listaItems" class="nav-btns button">
    {% for item in pedido.items %}
        <li class="registro">{{item.producto.nombre}}:  {{item.producto.precio}}.  Cantidad:{{item.cantidad}}  {{ include('item/_delete_form.html.twig') }}</li>
    {% endfor %}
        <li class="registro">TOTAL: {{total}}</li>
    </ul>
    <div class="nav-btns button">
        {% if is_granted('ROLE_ADMIN')%}
            <a href="{{path('app_pedido_index_all')}}"><button class="btn btn-warning">Volver a la lista de pedidos</button></a>
        {% else %}
            <a href="{{path('app_pedido_pago', {'id': pedido.id})}}" onclick="vaciarCarro()"><button class="btn btn-danger">Pagar</button></a>
            <a href="{{path('app_pedido_index', {'id': app.user.id}) }}"><button class="btn btn-warning">Volver a la lista de pedidos</button></a>
        {% endif %}
    </div>

    {# <a href="{{ path('app_pedido_edit', {'id': pedido.id}) }}">edit</a> #}

    {# {{ include('pedido/_delete_form.html.twig') }} #}
{% endblock %}