src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

use Symfony\Component\Validator\Constraints as Assert;
use App\Validator as AppAssert; //cargamos los ficheros del validador propio que hemos creado para aplciarlo sobre la clase en la que queremos usarlo

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Ya hay una cuenta de correo con este email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(message: 'El email {{ value }} no es valido.',)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message:'El campo nombre no puede estar vacio.',)]
    #[Assert\Length(min: 2, max: 12,
        minMessage: 'Tu nombre debe tener mas de {{ limit }} letras, ahora tiene {{ value }}.',
        maxMessage: 'Tu nombre no puede tener mas de {{ limit }} letras, ahora tiene {{ value }}.',
    )]

    //#[AppAssert\NombreUsuarioUnico] //como en "NombreUsuarioUnico" asignamos la validacion como 
                                    //"PROPERTY_CONSTRAINT", la tenemos que aplicar sobre el atributo concreto
    private ?string $nombre = null;

    #[ORM\Column(length: 500, nullable: true)]
    #[Assert\NotBlank(message:'El campo apellidos no puede estar vacio.',)]
    #[Assert\Length(max: 15, maxMessage: 'Tu apellido no puede tener mas de {{ limit }} letras, ahora tiene {{ value }}',)]
    private ?string $apellidos = null;

    #[ORM\Column(length: 600, nullable: true)]
    #[Assert\NotBlank(message:'El campo direccion no puede estar vacio.',)]
    private ?string $direccion = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_nacimiento = null;

    #[ORM\OneToMany(mappedBy: 'User', targetEntity: Pregunta::class, cascade: ['persist','remove'])]
    private Collection $preguntas;

    #[ORM\OneToMany(mappedBy: 'User', targetEntity: Respuesta::class, cascade: ['persist','remove'])]
    private Collection $respuestas;

    public function __construct()
    {
        $this->preguntas = new ArrayCollection();
        $this->respuestas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->apellidos;
    }

    public function setApellidos(?string $apellidos): self
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(?string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fecha_nacimiento;
    }

    public function setFechaNacimiento(?\DateTimeInterface $fecha_nacimiento): self
    {
        $this->fecha_nacimiento = $fecha_nacimiento;

        return $this;
    }

    /**
     * @return Collection<int, Pregunta>
     */
    public function getPreguntas(): Collection
    {
        return $this->preguntas;
    }

    public function addPregunta(Pregunta $pregunta): self
    {
        if (!$this->preguntas->contains($pregunta)) {
            $this->preguntas->add($pregunta);
            $pregunta->setUser($this);
        }

        return $this;
    }

    public function removePregunta(Pregunta $pregunta): self
    {
        if ($this->preguntas->removeElement($pregunta)) {
            // set the owning side to null (unless already changed)
            if ($pregunta->getUser() === $this) {
                $pregunta->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Respuesta>
     */
    public function getRespuestas(): Collection
    {
        return $this->respuestas;
    }

    public function addRespuesta(Respuesta $respuesta): self
    {
        if (!$this->respuestas->contains($respuesta)) {
            $this->respuestas->add($respuesta);
            $respuesta->setUser($this);
        }

        return $this;
    }

    public function removeRespuesta(Respuesta $respuesta): self
    {
        if ($this->respuestas->removeElement($respuesta)) {
            // set the owning side to null (unless already changed)
            if ($respuesta->getUser() === $this) {
                $respuesta->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre', TextType::class, [
                'label' => 'Nombre',
                'attr' => [
                    'autocomplete' => 'nombre',                     
                    'class' => 'input_formulario_registro'
                ],
            ])
            ->add('apellidos', TextType::class, [
                'label' => 'Apellidos',
                'attr' => [
                    'autocomplete' => 'apellidos',                     
                    'class' => 'input_formulario_registro'
                ],
            ])
            ->add('email', TextType::class, [
                'label' => 'Email',
                'attr' => [
                    'autocomplete' => 'email',                     
                    'class' => 'input_formulario_registro'
                ],
            ])
            ->add('plainPassword', RepeatedType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'type' => PasswordType::class,
                'first_options'  => ['label' => 'Password', 'hash_property_path' => 'password'],
                'second_options' => ['label' => 'Repita su password'],
                'mapped' => false,
                'attr' => [
                    'autocomplete' => 'new-password',
                    'class' => 'input_formulario_registro',
                    'placeholder' => 'Password'
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Por favor introduce una contraseña',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Tu contraseña debe tener al menos {{ limit }} caracteres',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ])
/*             ->add('verifyPassword', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'label' => 'Repita la password',
                'mapped' => false,
                'attr' => [
                    'autocomplete' => 'new-password',
                    'class' => 'input_formulario_registro',
                    'placeholder' => 'Verifique la password'
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Por favor introduce una contraseña',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Tu contraseña debe tener al menos {{ limit }} caracteres',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ]) */
            ->add('direccion', TextType::class, [
                'label' => 'Direccion',
                'attr' => [
                    'autocomplete' => 'direccion',                     
                    'class' => 'input_formulario_registro'
                ],
            ])
            ->add('fecha_nacimiento',DateType::Class, [
                'format' => 'dd-MM-yyyy',
                'years' => range(date('1950'), date('Y'))
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/edit/{id}', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user,
    UserPasswordHasherInterface $userPasswordHasher, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
            $userRepository->save($user, true);
            //Si el usuario es ADMIN, lo redirigimos a la lista de usuarios y si no lo es, a la pagina principal
            if ($this->isGranted('ROLE_ADMIN')){
                return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
            }else{
                return $this->redirectToRoute('app_producto_index', [], Response::HTTP_SEE_OTHER);
            }

            
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isGranted('ROLE_ADMIN')){
            if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
                $userRepository->remove($user, true);
            }
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }else{
            //aqui habria que meter a la Entity User un atributo "activo" true/false para 
            //que el usuario que quiera eliminar su perfil deje de tener acceso a dicho 
            //perfil, pero sin eliminar dicho perfil de la base de datos
            return $this->redirectToRoute('app_logout', [], Response::HTTP_SEE_OTHER);
        }
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('¿Estas seguro de que quieres eliminar a este usuario?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">Eliminar</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actualizar usuario{% endblock %}

{% block body %}
    <div class="container contenedor">
        <div class="row">
            <div class="col-xs-12 nav-btns button">
                <h1>Actualizar usuario</h1>

                {{ include('user/_form.html.twig', {'button_label': 'Actualizar'}) }}
                <div class="contenedor-btn">
                    {% if is_granted('ROLE_ADMIN')%}
                    <a href="{{ path('app_user_index') }}"><button class="btn btn-warning">Volver</button></a>
                    {% else %}
                    <a href="{{ path('app_producto_index') }}"><button class="btn btn-warning">Volver</button></a>
                    {% endif %}
                    {{ include('user/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>



{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
<section class="bg-light p-5" id="r_lista">
    <h1>Lista de usuarios</h1>
    <div class="table-responsive" id="no-more-tables">
    <table class="table bg-white">
        <thead class="bg-dark text-light">
            <tr>
                <th>Id</th>
                <th>Email</th>
                {# <th>Roles</th> #}
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>Direccion</th>
                <th>Fecha_nacimiento</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td data-title="Id usuario" class="registro">{{ user.id }}</td>
                <td data-title="email usuario" class="registro">{{ user.email }}</td>
                {# <td data-title="Role usuario" class="registro">{{ user.roles ? user.roles|json_encode : '' }}</td> #}
                <td data-title="Nombre usuario" class="registro">{{ user.nombre }}</td>
                <td data-title="Apellido usuario" class="registro">{{ user.apellidos }}</td>
                <td data-title="Direccion usuario" class="registro">{{ user.direccion }}</td>
                <td data-title="Fecha nacimiento" class="registro">{{ user.fechaNacimiento ? user.fechaNacimiento|date('Y-m-d') : '' }}</td>
                <td data-title="Botones usuario">
                    <div class="contenedor-btn  nav-btns button">
                        <a  href="{{ path('app_user_show', {'id': user.id}) }}"><button class="btn btn-primary">Detalles</button></a>
                        <a  href="{{ path('app_user_edit', {'id': user.id}) }}"><button class="btn btn-warning">Actualizar</button></a>
                        {{ include('user/_delete_form.html.twig') }}
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td data-title="Not found usuario" colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
        </div>
</section>
    {# <a href="{{ path('app_user_new') }}">Create new</a> #}
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <ul id="listaCarrito" class="listaCarrito"></ul>
    <style>
        @media only screen and (max-width: 1023px) {
            .img-fluid {
                display:none;
            }
        }
    </style>


<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-12 col-lg-6">
            <div class="well col-sm-12 d-inline-flex">
                <div class="col-sm-4 col-xs-none">
                    <img class="img-fluid" src="https://png.pngitem.com/pimgs/s/150-1503945_transparent-user-png-default-user-image-png-png.png">
                </div>
                
                <div class="col-sm-8 col-xs-12">
                    <h4>{{ user.nombre }} {{ user.apellidos }}</h4>
                    <p><strong>Nº de usuario: </strong> {{ user.id }} </p>
                    <p class="registro" style="visibility: hidden;">{{ user.id }}</p>
                    <p><strong>Correo: </strong>{{ user.email }}</p>
                    <p><strong>Dirección: </strong>{{ user.direccion }}</p>
                    <p><strong>Fecha de nacimiento: </strong>{{ user.fechaNacimiento ? user.fechaNacimiento|date('Y-m-d') : '' }} </p>
                    <div class="justify-content-center nav-btns button">
                        <a href="{{ path('app_user_index') }}"><button class="btn btn-primary">Volver</button></a>
                        <a href="{{ path('app_user_edit', {'id': user.id}) }}"><button class="btn btn-warning">Actualizar</button></a>
                        <span>{{ include('user/_delete_form.html.twig') }}</span>
                    </div>
                </div>             
            </div>                    
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-12 col-lg-12">
            <div class="well col-sm-12 d-inline-flex">         
                <div id="listadoPreguntas" style='width: 100%;'></div>        
            </div>                    
		</div>
	</div>
</div>
    
    
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ asset('js/preguntasUsuarios.js') }}"></script>
{% endblock %}